In [1]:
import numpy as np

In [2]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

# 1) How many negative numbers are there?

In [3]:
a[a < 0]

array([-2, -1, -6, -7])

In [4]:
len(a[a < 0])

4

## 2) How many positive numbers are there?

In [5]:
a[a > 0]

array([ 4, 10, 12, 23,  3])

In [6]:
len(a[a > 0])

5

## 3) How many even positive numbers are there?

In [7]:
a[(a > 0) & (a % 2 == 0)]

array([ 4, 10, 12])

In [8]:
len(a[(a > 0) & (a % 2 == 0)])

3

## 4) If you were to add 3 to each data point, how many positive numbers would there be?

In [9]:
b = a + 3

b

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3, -3,  6, -4])

In [10]:
b[b > 0]

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3,  6])

In [11]:
len(b[b > 0])

10

## 5) If you squared each number, what would the new mean and standard deviation be?

In [12]:
c = a ** 2

c

array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

In [13]:
a.mean()

3.0

In [14]:
c.mean()

74.0

In [15]:
a.std()

8.06225774829855

In [16]:
c.std()

144.0243035046516

## 6) A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering

In [17]:
d = a - 3

d

array([  1,   7,   9,  20,  -5,  -4,  -3,  -3,  -3,  -9,   0, -10])

In [18]:
d.mean()

0.0

## 7) Calculate the z-score for each data point. Recall that the z-score is given by:

Z = (x − μ) / σ


In [19]:
import scipy.stats as stats

stats.zscore(a)

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [20]:
z = (a - 3) / (a.std())

z

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

## 8) Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and add your solutions.

In [21]:
## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

- Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

In [22]:
sum_of_a = sum(a)

sum_of_a

55

- Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

In [23]:
min_of_a = min(a)

min_of_a

1

- Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

In [24]:
max_of_a = max(a)

max_of_a

10

- Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

In [26]:
mean_of_a = np.mean(a)

mean_of_a

5.5

- Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

In [27]:
product_of_a = np.prod(a)

product_of_a

3628800

- Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

In [29]:
squares_of_a = np.array(a) ** 2

squares_of_a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

- Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

In [31]:
odds_in_a = np.array(a)[np.array(a) % 2 == 1]

odds_in_a

array([1, 3, 5, 7, 9])

- Exercise 8 - Make a variable named evens_in_a. It should hold only the evens

In [32]:
evens_in_a = np.array(a)[np.array(a) % 2 == 0
                        ]

evens_in_a

array([ 2,  4,  6,  8, 10])

In [33]:
## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.
b = [
    [3, 4, 5],
    [6, 7, 8]
]

In [34]:
b

[[3, 4, 5], [6, 7, 8]]